name: 'Terraform CI/CD'

on:
  push:
    branches:
      - main
      - test
      - dev
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      # This maps the Git branch name to the correct Terraform workspace
      TF_WORKSPACE: ${{ (github.ref == 'refs/heads/main' && 'prod') || (github.ref == 'refs/heads/test' && 'test') || 'dev' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Workspace Selection
        run: terraform workspace select $TF_WORKSPACE || terraform workspace new $TF_WORKSPACE

      - name: Terraform Plan
        id: plan
        run: terraform plan -var="environment=$TF_WORKSPACE" -no-color
        # For pull requests, we only run a plan, not an apply

      - name: Terraform Apply
        if: github.ref != 'refs/heads/pull/*' && github.event_name == 'push'
        run: terraform apply -auto-approve -var="environment=$TF_WORKSPACE"

